### ISSUE TITLE
Can't find input_INTEL_g2o

### ISSUE THREAD

**Issue by jdmartin86** [JeffLIrion/python-graphslam#2]
After pip installing the package and attempting to run the example, I get the following error message:

`
FileNotFoundError: [Errno 2] No such file or directory: 'input_INTEL_g2o'
`

Are any additional steps required to locate this file / directory?

**Comment by JeffLIrion** [comment]
I didn't include it in the repo because it's not my dataset. But I did put a link in the README: https://lucacarlone.mit.edu/datasets/

**Comment by JeffLIrion** [comment]
Did you get this sorted out?

**Comment by jdmartin86** [comment]
Yes, thank you.
